### ISSUE TITLE
Add DevSetup folder which helps the Development tools required for this project

### ISSUE THREAD

**Issue by naz-hage** [naz-hage/hbs-lib#5]
Every project should have a statement about the development tools required to build and test.  This project is no exception.
The acceptance criteria is:
- Add a DevSetup folder
- Follow the the ntools project
- A json file which list the requied tools
- a powershell script which installs all required tools

**Comment by ahmdhjj** [comment]
@naz-hage should we consider removing 7-zip and MongoDB? Are they needed?

| App name           | Target version | Installed version |
|--------------------|----------------|-------------------|
| Dotnet Runtime     | 8.0.1          | 8.0.424.16909     |
| Visual Studio 2022 | 17.0.0         | 17.8.34511.84     |
| 7-zip              | 23.01          | 23.1.0.0          |
| Git for Windows    | 2.44.0         | 2.44.0.1          |
| Powershell         | 7.4.2          | 7.4.2.500         |
| Visual Studio Code | 1.88.1.0       | 1.88.1.0          |
| Nuget              | 6.9.1.3        | 6.9.1.3           |
| SysInternals       | 2.90.0.0       | 2.90.0.0          |
| MongoDB            | 7.0.8          | 7.0.8.0           |
| SQLite             | 3.45.2         | 3.45.2.0          |
| SQLite tools       | 3.45.2         | 3.45.2.0          |

**Comment by naz-hage** [comment]
Yes, we can remove 7-zip and MongoDB.  They are not needed.
